# Client -> Server
JOIN_ROOM = "join_room"
LEAVE_ROOM = "leave_room"
SEND_MESSAGE = "send_message"
EDIT_MESSAGE = "edit_message"
DELETE_MESSAGE = "delete_message"
FORWARD_MESSAGE = "forward_message"
SEND_STICKER = "send_sticker"
ADD_REACTION = "add_reaction"
REMOVE_REACTION = "remove_reaction"
TYPING = "typing"
STOP_TYPING = "stop_typing"

# Server -> Client
RECEIVE_MESSAGE = "receive_message"
MESSAGE_EDITED = "message_edited"
MESSAGE_DELETED = "message_deleted"
REACTION_ADDED = "reaction_added"
REACTION_REMOVED = "reaction_removed"
USER_ONLINE = "user_online"
USER_OFFLINE = "user_offline"
ROOM_EXPIRED = "room_expired"
CHAT_RESET = "chat_reset"
AI_SUMMARY_READY = "ai_summary_ready"
MESSAGE_TRANSLATED = "message_translated"
